### ISSUE TITLE
Usage with React Native

### ISSUE THREAD

**Issue by amaury1093** [outmoded/sntp#36]
#### Support plan

* *which support plan is this issue covered by?* Community
* *is this issue currently blocking your project?* yes
* *is this issue affecting a production system?* no

#### Context

* *node version*: 13.6.0 (but using it in React Native)
* *module version with issue*: 4.0.0
* *last module version without issue*: unknown
* *environment* (e.g. node, browser, native): React Native
* *used with* (e.g. hapi application, another framework, standalone, ...): React Native
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

Concretely, in my code, I'm doing this:
```js
import Hawk from '@hapi/hawk';
```

And `@hapi/hawk` depends on `@hapi/sntp`.

#### What was the result you got?

<img width="397" alt="Screenshot 2020-01-13 at 12 48 42" src="https://user-images.githubusercontent.com/1293565/72254140-7c834180-3603-11ea-9da2-f4f6a6124b1f.png">

#### What result did you expect?

Be able to use `@hapi/sntp`

#### Notes

I can think of 2 solutions:
1. Add a dgram polyfill in my react native app, e.g. https://github.com/tradle/react-native-udp
2. Change `@hapi/sntp` to not use nodejs-specific API. e.g.: would it be possible to replace dgram with ws/http requests?

#### Additional question

How does `@hapi/sntp` work in browser (which don't support UDP)? If there's a plan to make `@hapi/sntp` work in browser too, then the solution 2 above seems to be the optimal choice.

**Comment by hueniverse** [comment]
If you are trying to use the hawk client in the browser, import just that directly (`lib/browser.js`), not the entire module as it is designed to work only server-side on node.
