### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by guimard** [outmoded/sntp#37]
Hi,

a simple `npm i && npm run test` reports a failure between @hapi/sntp and @hapi/teamwork:
```
node_modules/@hapi/teamwork/lib/index.js:8
    #meetings = null;
    ^

SyntaxError: Invalid or unexpected token
```
Is there a missing transpilation ?

**Comment by Marsup** [comment]
Latest versions require node 12+, and I'm going to assume you're using an older one since you didn't fill the issue template.
